# Generated by Django 3.1.4 on 2020-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='../../static/profile_pictures/'),
        ),
    ]
