# Generated by Django 3.1.4 on 2020-12-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('translator', models.CharField(blank=True, max_length=100, null=True)),
                ('book_price', models.FloatField(help_text='The price of book which is printed on the cover')),
                ('sell_price', models.FloatField(help_text='The price which the user wants to sell')),
                ('is_new', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='accounts.account')),
            ],
        ),
    ]
